version: '3.1'
services:
  pgdb:
    image: postgres:latest
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: immoscrap
    ports:
      - "5432:5432" 
    volumes:
      - "./db:/var/lib/postgresql/data" # docker-compose exec pgdb psql -U root -W immoscrap
  admin:
    image: adminer
    ports:
      - "8080:8080"
